package com.netcracker.financeapp.mapping;
// Generated Feb 11, 2017 12:29:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Income generated by hbm2java
 */
public class Income  implements java.io.Serializable {


     private int idIncome;
     private Type type;
     private Integer value;
     private String description;
     private Date date;

    public Income() {
    }

	
    public Income(int idIncome) {
        this.idIncome = idIncome;
    }
    public Income(int idIncome, Type type, Integer value, String description, Date date) {
       this.idIncome = idIncome;
       this.type = type;
       this.value = value;
       this.description = description;
       this.date = date;
    }
   
    public int getIdIncome() {
        return this.idIncome;
    }
    
    public void setIdIncome(int idIncome) {
        this.idIncome = idIncome;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


