package com.netcracker.financeapp.mapping;
// Generated Feb 11, 2017 12:29:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private int idType;
     private String name;
     private Set<Income> incomes = new HashSet<Income>(0);
     private Set<Spendings> spendingses = new HashSet<Spendings>(0);

    public Type() {
    }

	
    public Type(int idType) {
        this.idType = idType;
    }
    public Type(int idType, String name, Set<Income> incomes, Set<Spendings> spendingses) {
       this.idType = idType;
       this.name = name;
       this.incomes = incomes;
       this.spendingses = spendingses;
    }
   
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Income> getIncomes() {
        return this.incomes;
    }
    
    public void setIncomes(Set<Income> incomes) {
        this.incomes = incomes;
    }
    public Set<Spendings> getSpendingses() {
        return this.spendingses;
    }
    
    public void setSpendingses(Set<Spendings> spendingses) {
        this.spendingses = spendingses;
    }




}


